// packages/frontend/src/components/quiz/FeedbackDisplay.svelte
<script lang="ts">
  import { formatForDisplay, type SubmissionResult, type QuizQuestion, type RevealResult } from '@lingua-quiz/core';
  import { Button } from '$lib/components/ui/button';
  import { RefreshCw } from 'lucide-svelte';
  import type { QuizFeedback } from '../../api-types';

  interface Props {
    feedback?: SubmissionResult | QuizFeedback | RevealResult | null;
    questionForFeedback?: QuizQuestion | null;
    onRetry?: () => void;
  }

  const { feedback = null, questionForFeedback = null, onRetry }: Props = $props();

  let retryButtonRef = $state<HTMLButtonElement | null>(null);

  const isRevealResult = $derived(feedback && 'correctAnswerText' in feedback && !('isCorrect' in feedback) && !('isSuccess' in feedback));

  const isSuccess = $derived.by(() => {
    if (!feedback) return false;
    if ('isSuccess' in feedback) return feedback.isSuccess;
    if ('isCorrect' in feedback) return feedback.isCorrect;
    return false;
  });

  const isQuizFeedback = $derived(feedback && 'isSuccess' in feedback && !('isCorrect' in feedback));
  const showRetry = $derived(isQuizFeedback && !isSuccess && onRetry);

  const feedbackMessage = $derived.by(() => {
    if (!feedback) return '';
    if ('message' in feedback) return feedback.message;
    const questionText = questionForFeedback?.questionText ?? '';
    return `${questionText} = ${formatForDisplay(feedback.correctAnswerText)}`;
  });

  const feedbackClass = $derived.by(() => {
    if (isRevealResult) return 'revealed';
    if (isSuccess) return 'success';
    return 'error';
  });
</script>

{#if feedback}
  <div class="feedback-container" role="alert" aria-live="polite">
    <div class="feedback-text {feedbackClass}">
      <span class="feedback-icon" aria-hidden="true"></span>
      <span class="feedback-message">{feedbackMessage}</span>
    </div>
    {#if showRetry}
      <Button
        variant="outline"
        onclick={onRetry}
        class="retry-btn"
        bind:ref={retryButtonRef}
      >
        <RefreshCw size={16} />
        <span>Try again</span>
      </Button>
    {/if}
  </div>
{/if}

<style>
  .feedback-container {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-sm);
  }

  .feedback-text {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: var(--spacing-sm);
    padding: var(--spacing-sm) var(--spacing-md);
    min-height: 2.5rem;
    font-weight: bold;
    background-color: var(--container-bg);
    border: 1px solid var(--input-border-color);
    border-radius: var(--radius-md);
    text-align: center;
  }

  .feedback-text.success {
    color: var(--success-color);
    border-color: var(--success-color);
    background-color: color-mix(in oklch, var(--success-color) 10%, var(--container-bg));
    box-shadow: 0 0 0 1px var(--success-color);
    animation: success-pulse 0.4s ease-out;
  }

  .feedback-text.success .feedback-icon::before {
    content: '✓';
    display: inline-block;
    animation: icon-pop 0.3s ease-out;
  }

  .feedback-text.error {
    color: var(--error-color);
    border-color: var(--error-color);
    background-color: color-mix(in oklch, var(--error-color) 10%, var(--container-bg));
    box-shadow: 0 0 0 1px var(--error-color);
    animation: shake 0.5s ease-out;
  }

  .feedback-text.error .feedback-icon::before {
    content: '✗';
  }

  .feedback-text.revealed {
    color: var(--color-muted-foreground);
    animation: fade-in 0.2s ease-out;
  }

  .feedback-text.revealed .feedback-icon::before {
    content: '○';
  }

  .feedback-text .feedback-icon::before {
    color: inherit;
    font-size: 1.2em;
  }

  @keyframes success-pulse {
    0% {
      transform: scale(0.95);
      opacity: 0;
    }
    50% {
      transform: scale(1.02);
    }
    100% {
      transform: scale(1);
      opacity: 1;
    }
  }

  @keyframes icon-pop {
    0% {
      transform: scale(0);
    }
    50% {
      transform: scale(1.3);
    }
    100% {
      transform: scale(1);
    }
  }

  @keyframes shake {
    0%, 100% {
      transform: translateX(0);
    }
    10%, 30%, 50%, 70%, 90% {
      transform: translateX(-6px);
    }
    20%, 40%, 60%, 80% {
      transform: translateX(6px);
    }
  }

  @keyframes fade-in {
    from {
      opacity: 0;
      transform: translateY(-4px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  :global(.retry-btn) {
    width: 100%;
  }

  @media (prefers-reduced-motion: reduce) {
    .feedback-text.success,
    .feedback-text.error,
    .feedback-text.revealed {
      animation: none;
    }

    .feedback-text.success .feedback-icon::before {
      animation: none;
    }
  }
</style>

// packages/frontend/src/features/quiz/components/FeedbackDisplay.tsx
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { formatForDisplay, type SubmissionResult, type QuizQuestion, type RevealResult } from '@lingua-quiz/core';
import { RefreshCw, Check, X, Circle } from 'lucide-react';
import { cn } from '@shared/utils';
import { Button } from '@shared/ui';
import type { QuizFeedback } from '@api/types';

interface FeedbackDisplayProps {
  feedback?: SubmissionResult | QuizFeedback | RevealResult | null;
  questionForFeedback?: QuizQuestion | null;
  onRetry?: () => void;
}

export function FeedbackDisplay({
  feedback = null,
  questionForFeedback = null,
  onRetry,
}: FeedbackDisplayProps): React.JSX.Element | null {
  const { t } = useTranslation();

  const isRevealResult =
    feedback !== null && 'correctAnswerText' in feedback && !('isCorrect' in feedback) && !('isSuccess' in feedback);

  const isSuccess = useMemo(() => {
    if (feedback === null) return false;
    if ('isSuccess' in feedback) return feedback.isSuccess;
    if ('isCorrect' in feedback) return feedback.isCorrect;
    return false;
  }, [feedback]);

  const isQuizFeedback = feedback !== null && 'isSuccess' in feedback && !('isCorrect' in feedback);
  const showRetry = isQuizFeedback && !isSuccess && onRetry !== undefined;

  const feedbackMessage = useMemo(() => {
    if (feedback === null) return '';
    if ('message' in feedback) return feedback.message;
    const questionText = questionForFeedback?.questionText ?? '';
    return `${questionText} = ${formatForDisplay(feedback.correctAnswerText)}`;
  }, [feedback, questionForFeedback]);

  if (feedback === null) return null;

  return (
    <div className="feedback-container flex flex-col gap-3" role="alert" aria-live="polite">
      <div
        className={cn(
          'flex items-center justify-center gap-3 px-4 py-3 min-h-10 font-semibold rounded-lg border text-center transition-all',
          isRevealResult && 'text-muted-foreground bg-muted/50 border-border animate-fade-in',
          isSuccess && 'text-success bg-success/10 border-success ring-1 ring-success animate-success-pulse',
          !isRevealResult &&
            !isSuccess &&
            'text-destructive bg-destructive/10 border-destructive ring-1 ring-destructive animate-shake',
        )}
      >
        <span className="text-lg" aria-hidden="true">
          {isRevealResult ? (
            <Circle size={18} />
          ) : isSuccess ? (
            <Check size={18} className="animate-icon-pop" />
          ) : (
            <X size={18} />
          )}
        </span>
        <span
          className={cn(
            'feedback-text',
            isRevealResult && 'revealed',
            isSuccess && 'success',
            !isRevealResult && !isSuccess && 'error',
          )}
        >
          {feedbackMessage}
        </span>
      </div>
      {showRetry && (
        <Button variant="outline" onClick={onRetry} className="w-full">
          <RefreshCw size={16} />
          <span>{t('quiz.tryAgain')}</span>
        </Button>
      )}
      <style>{`
        @keyframes fade-in {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        .animate-fade-in {
          animation: fade-in 0.2s ease-out;
        }
        @keyframes success-pulse {
          0%, 100% { transform: scale(1); }
          50% { transform: scale(1.02); }
        }
        .animate-success-pulse {
          animation: success-pulse 0.3s ease-out;
        }
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          25% { transform: translateX(-4px); }
          75% { transform: translateX(4px); }
        }
        .animate-shake {
          animation: shake 0.3s ease-out;
        }
        @keyframes icon-pop {
          0% { transform: scale(0); }
          50% { transform: scale(1.3); }
          100% { transform: scale(1); }
        }
        .animate-icon-pop {
          animation: icon-pop 0.3s ease-out;
        }
      `}</style>
    </div>
  );
}
