// packages/frontend/src/components/quiz/LevelChangeAnimation.svelte
<script lang="ts">
  interface Props {
    isVisible?: boolean;
    isLevelUp?: boolean;
    fromLevel?: string;
    toLevel?: string;
    onComplete?: () => void;
  }

  // eslint-disable-next-line prefer-const -- Svelte 5 requires let for $bindable props
  let { isVisible = $bindable(false), isLevelUp = true, fromLevel, toLevel, onComplete }: Props =
    $props();

  let animationElement = $state<HTMLDivElement | null>(null);

  const levelLabel = (level: string | undefined) => level?.replace('LEVEL_', 'Level ') ?? '';

  $effect(() => {
    if (!isVisible || !animationElement) return;

    animationElement.style.animation = 'none';
    animationElement.offsetHeight;
    animationElement.style.animation = '';

    const timer = setTimeout(() => {
      onComplete?.();
    }, 1500);

    return () => clearTimeout(timer);
  });
</script>

{#if isVisible}
  <div
    bind:this={animationElement}
    class="level-change-animation {isLevelUp ? 'level-up' : 'level-down'}"
    role="alert"
    aria-live="polite"
  >
    <div class="animation-content">
      <div class="icon">{isLevelUp ? '⬆️' : '⬇️'}</div>
      <div class="text-content">
        <div class="title">{isLevelUp ? 'Level Up!' : 'Level Down'}</div>
        {#if fromLevel && toLevel}
          <div class="levels">{levelLabel(fromLevel)} → {levelLabel(toLevel)}</div>
        {/if}
      </div>
    </div>
  </div>
{/if}

<style>
  .level-change-animation {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 1000;
    pointer-events: none;
  }

  .level-up {
    animation: level-up-animation 1.5s ease-out forwards;
  }

  .level-down {
    animation: level-down-animation 1.5s ease-out forwards;
  }

  .animation-content {
    background: var(--color-surface);
    border-radius: var(--radius-xl);
    padding: var(--spacing-md) var(--spacing-xl);
    box-shadow: var(--shadow-xl);
    backdrop-filter: blur(10px);
    border: 2px solid;
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    opacity: 0.95;
  }

  .icon {
    font-size: 1.5rem;
  }

  .text-content {
    display: flex;
    flex-direction: column;
  }

  .title {
    font-weight: bold;
    font-size: var(--font-size-lg);
  }

  .levels {
    font-size: var(--font-size-sm);
    opacity: 0.8;
  }

  .level-up .animation-content {
    border-color: var(--color-level-up-border);
    color: var(--color-level-up);
  }

  .level-down .animation-content {
    border-color: var(--color-level-down-border);
    color: var(--color-level-down);
  }

  @keyframes level-up-animation {
    0% {
      transform: translate(-50%, -50%) scale(0.5);
      opacity: 0;
    }

    20% {
      transform: translate(-50%, -50%) scale(1.2);
      opacity: 1;
    }

    40% {
      transform: translate(-50%, -50%) scale(1);
    }

    100% {
      transform: translate(-50%, -60%) scale(1);
      opacity: 0;
    }
  }

  @keyframes level-down-animation {
    0% {
      transform: translate(-50%, -50%) scale(0.5);
      opacity: 0;
    }

    20% {
      transform: translate(-50%, -50%) scale(1.2);
      opacity: 1;
    }

    40% {
      transform: translate(-50%, -50%) scale(1);
    }

    100% {
      transform: translate(-50%, -40%) scale(1);
      opacity: 0;
    }
  }
</style>

// packages/frontend/src/features/quiz/components/LevelChangeAnimation.tsx
import { useEffect, useRef, useCallback } from 'react';
import { ArrowUp, ArrowDown } from 'lucide-react';
import { cn } from '@shared/utils';

interface LevelChangeAnimationProps {
  isVisible?: boolean;
  isLevelUp?: boolean;
  fromLevel?: string;
  toLevel?: string;
  onComplete?: () => void;
}

const levelLabel = (level: string | undefined) => level?.replace('LEVEL_', 'Level ') ?? '';

export function LevelChangeAnimation({
  isVisible = false,
  isLevelUp = true,
  fromLevel,
  toLevel,
  onComplete,
}: LevelChangeAnimationProps): React.JSX.Element | null {
  const animationRef = useRef<HTMLDivElement>(null);

  const triggerAnimation = useCallback(() => {
    const element = animationRef.current;
    if (element === null) return;

    element.style.animation = 'none';
    void element.offsetHeight;
    element.style.animation = '';

    const timer = setTimeout(() => {
      onComplete?.();
    }, 1200);

    return () => {
      clearTimeout(timer);
    };
  }, [onComplete]);

  useEffect(() => {
    if (!isVisible) return;
    return triggerAnimation();
  }, [isVisible, triggerAnimation]);

  if (!isVisible) return null;

  return (
    <div
      ref={animationRef}
      className={cn(
        'fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 pointer-events-none',
        isLevelUp ? 'animate-level-up' : 'animate-level-down',
      )}
      role="alert"
      aria-live="polite"
    >
      <div
        className={cn(
          'flex items-center gap-3 px-6 py-4 rounded-lg border-2 bg-card/95 backdrop-blur-sm shadow-lg',
          isLevelUp ? 'border-success text-success' : 'border-destructive text-destructive',
        )}
      >
        <span className="text-2xl">{isLevelUp ? <ArrowUp size={24} /> : <ArrowDown size={24} />}</span>
        <div className="flex flex-col">
          <span className="font-bold text-lg">{isLevelUp ? 'Level Up!' : 'Level Down'}</span>
          {fromLevel !== undefined && toLevel !== undefined && (
            <span className="text-sm opacity-80">
              {levelLabel(fromLevel)} → {levelLabel(toLevel)}
            </span>
          )}
        </div>
      </div>
      <style>{`
        @keyframes level-up {
          0% { transform: translate(-50%, -50%) scale(0.5); opacity: 0; }
          20% { transform: translate(-50%, -50%) scale(1.1); opacity: 1; }
          40% { transform: translate(-50%, -50%) scale(1); }
          80% { transform: translate(-50%, -50%) scale(1); opacity: 1; }
          100% { transform: translate(-50%, -100%) scale(0.8); opacity: 0; }
        }
        @keyframes level-down {
          0% { transform: translate(-50%, -50%) scale(0.5); opacity: 0; }
          20% { transform: translate(-50%, -50%) scale(1.1); opacity: 1; }
          40% { transform: translate(-50%, -50%) scale(1); }
          80% { transform: translate(-50%, -50%) scale(1); opacity: 1; }
          100% { transform: translate(-50%, 0%) scale(0.8); opacity: 0; }
        }
        .animate-level-up {
          animation: level-up 1.2s ease-out forwards;
        }
        .animate-level-down {
          animation: level-down 1.2s ease-out forwards;
        }
      `}</style>
    </div>
  );
}
