// packages/frontend/src/components/quiz/UsageExamples.svelte
<script lang="ts">
  interface Props {
    examples?: { source: string; target: string } | null;
  }

  const { examples = null }: Props = $props();
</script>

{#if examples}
  <div class="flex flex-col gap-2">
    {#if examples.source}
      <p class="example-text">{examples.source}</p>
    {/if}
    {#if examples.target}
      <p class="example-text">{examples.target}</p>
    {/if}
  </div>
{/if}

<style>
  .example-text {
    background-color: var(--color-muted);
    padding: var(--spacing-sm);
    border-radius: var(--radius-sm);
    margin: 0;
    font-style: italic;
  }
</style>

// packages/frontend/src/features/quiz/components/UsageExamples.tsx
interface UsageExamplesProps {
  examples?: { source: string; target: string } | null;
}

export function UsageExamples({ examples = null }: UsageExamplesProps): React.JSX.Element | null {
  if (examples === null) return null;

  return (
    <div className="flex flex-col gap-2">
      {examples.source !== '' && <p className="example-text">{examples.source}</p>}
      {examples.target !== '' && <p className="example-text">{examples.target}</p>}
      <style>{`
        .example-text {
          background-color: var(--color-muted);
          padding: var(--spacing-sm);
          border-radius: var(--radius-sm);
          margin: 0;
          font-style: italic;
        }
      `}</style>
    </div>
  );
}
