// packages/frontend/src/components/quiz/UserActions.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { Button } from '$lib/components/ui/button';
  import { Settings } from 'lucide-svelte';
  import { _ } from 'svelte-i18n';

  interface Props {
    username: string | null;
  }

  const { username }: Props = $props();

  async function navigateToSettings() {
    await goto('/settings');
  }
</script>

<div class="actions">
  <Button variant="outline" onclick={navigateToSettings} class="w-full">
    <Settings size={16} />
    <span>{$_('common.settings')} ({username})</span>
  </Button>
</div>

// packages/frontend/src/features/quiz/components/UserActions.tsx
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Settings } from 'lucide-react';
import { Button } from '@shared/ui';

interface UserActionsProps {
  username: string | null;
}

export function UserActions({ username }: UserActionsProps): React.JSX.Element {
  const { t } = useTranslation();
  const navigate = useNavigate();

  const navigateToSettings = () => {
    void navigate('/settings');
  };

  return (
    <div className="actions">
      <Button variant="outline" onClick={navigateToSettings} className="w-full">
        <Settings size={16} />
        <span>
          {t('common.settings')} ({username})
        </span>
      </Button>
    </div>
  );
}
