// packages/frontend/src/shared/components/ConfirmDialog.tsx
import { useEffect, useRef } from 'react';
import { AlertTriangle, type LucideIcon } from 'lucide-react';
import { Button } from '@shared/ui';

type ButtonVariant = 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';

interface ConfirmDialogProps {
  open: boolean;
  title: string;
  description: string;
  confirmLabel: string;
  cancelLabel?: string;
  confirmVariant?: ButtonVariant;
  onConfirm: () => void;
  onCancel: () => void;
  icon?: LucideIcon;
}

export function ConfirmDialog({
  open,
  title,
  description,
  confirmLabel,
  cancelLabel = 'Cancel',
  confirmVariant = 'destructive',
  onConfirm,
  onCancel,
  icon: IconComponent = AlertTriangle,
}: ConfirmDialogProps): React.JSX.Element {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const confirmButtonRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (dialog === null) return;

    if (open) {
      dialog.showModal();
      confirmButtonRef.current?.focus();
    } else {
      dialog.close();
    }
  }, [open]);

  const handleCancel = (e: React.SyntheticEvent): void => {
    e.preventDefault();
    onCancel();
  };

  const handleClick = (e: React.MouseEvent): void => {
    if (e.target === dialogRef.current) {
      onCancel();
    }
  };

  return (
    <dialog
      ref={dialogRef}
      className="confirm-dialog"
      aria-labelledby="confirm-dialog-title"
      aria-describedby="confirm-dialog-desc"
      onCancel={handleCancel}
      onClick={handleClick}
    >
      <div className="confirm-dialog-content">
        <IconComponent size={20} className="warning-icon" />
        <span id="confirm-dialog-title" className="confirm-title text-base">
          {title}
        </span>
        <span id="confirm-dialog-desc" className="confirm-desc text-sm">
          {description}
        </span>
        <div className="confirm-actions">
          <Button ref={confirmButtonRef} size="sm" variant={confirmVariant} onClick={onConfirm}>
            {confirmLabel}
          </Button>
          <Button size="sm" variant="ghost" onClick={onCancel}>
            {cancelLabel}
          </Button>
        </div>
      </div>
      <style>{`
        .confirm-dialog {
          border: none;
          border-radius: var(--radius-lg);
          padding: 0;
          max-width: min(90vw, 400px);
          background: transparent;
        }

        .confirm-dialog::backdrop {
          background: rgb(0 0 0 / 0.5);
          backdrop-filter: blur(4px);
        }

        .confirm-dialog[open] {
          animation: dialog-appear 0.2s ease-out;
        }

        @keyframes dialog-appear {
          from {
            opacity: 0;
            transform: scale(0.95);
          }
          to {
            opacity: 1;
            transform: scale(1);
          }
        }

        .confirm-dialog-content {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: var(--spacing-xs);
          padding: var(--spacing-lg);
          background-color: var(--color-surface);
          border: 1px solid var(--color-border);
          border-radius: var(--radius-lg);
          text-align: center;
          box-shadow: var(--shadow-xl);
        }

        .confirm-dialog .warning-icon {
          color: var(--color-secondary);
        }

        .confirm-title {
          font-weight: var(--font-weight-semibold);
        }

        .confirm-desc {
          color: var(--color-text-muted);
        }

        .confirm-actions {
          display: flex;
          gap: var(--spacing-sm);
          margin-top: var(--spacing-sm);
        }

        @media (prefers-reduced-motion: reduce) {
          .confirm-dialog[open] {
            animation: none;
          }
        }
      `}</style>
    </dialog>
  );
}

// packages/frontend/src/components/quiz/ConfirmDialog.svelte
<script lang="ts">
  export let open = false;
  export let title = 'Confirm';
  export let message = 'Are you sure?';
  export let confirmText = 'Confirm';
  export let cancelText = 'Cancel';
  export let onConfirm: () => void = () => {};
  export let onCancel: () => void = () => {};

  let dialogElement: HTMLDialogElement;

  $: if (dialogElement) {
    if (open) {
      dialogElement.showModal();
    } else {
      dialogElement.close();
    }
  }

  function handleConfirm() {
    onConfirm();
    open = false;
  }

  function handleCancel() {
    onCancel();
    open = false;
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape') {
      handleCancel();
    }
  }

  function handleBackdropClick(event: MouseEvent) {
    if (event.target === dialogElement) {
      handleCancel();
    }
  }
</script>

<dialog
  bind:this={dialogElement}
  on:keydown={handleKeydown}
  on:click={handleBackdropClick}
  aria-labelledby="dialog-title"
  aria-describedby="dialog-message"
>
  <div class="dialog-content">
    <h2 id="dialog-title">{title}</h2>
    <p id="dialog-message">{message}</p>
    <div class="dialog-actions">
      <button type="button" class="cancel-btn" on:click={handleCancel}>
        {cancelText}
      </button>
      <button type="button" class="confirm-btn" on:click={handleConfirm}>
        {confirmText}
      </button>
    </div>
  </div>
</dialog>

<style>
  dialog {
    border: none;
    border-radius: var(--radius-lg);
    padding: 0;
    max-width: 400px;
    width: 90%;
    box-shadow: 0 25px 50px -12px rgb(0 0 0 / 25%);
    background-color: var(--container-bg);
  }

  dialog::backdrop {
    background-color: rgb(0 0 0 / 50%);
    backdrop-filter: blur(4px);
  }

  dialog[open] {
    animation: dialog-open 0.2s ease-out;
  }

  @keyframes dialog-open {
    from {
      opacity: 0;
      transform: scale(0.95);
    }

    to {
      opacity: 1;
      transform: scale(1);
    }
  }

  .dialog-content {
    padding: var(--spacing-lg);
  }

  h2 {
    margin: 0 0 var(--spacing-md) 0;
    font-size: var(--font-size-lg);
    font-weight: 600;
    color: var(--text-color);
  }

  p {
    margin: 0 0 var(--spacing-lg) 0;
    color: var(--text-color);
    line-height: 1.5;
  }

  .dialog-actions {
    display: flex;
    gap: var(--spacing-sm);
    justify-content: flex-end;
  }

  button {
    padding: var(--spacing-sm) var(--spacing-md);
    border-radius: var(--radius-md);
    font-weight: 500;
    cursor: pointer;
    transition: all var(--transition-speed) ease;
  }

  .cancel-btn {
    background-color: transparent;
    border: 1px solid var(--input-border-color);
    color: var(--text-color);
  }

  .cancel-btn:hover {
    background-color: var(--disabled-bg);
  }

  .confirm-btn {
    background-color: var(--primary-color);
    border: none;
    color: white;
  }

  .confirm-btn:hover {
    background-color: var(--primary-hover);
  }

  .confirm-btn:focus-visible,
  .cancel-btn:focus-visible {
    outline: 2px solid var(--primary-color);
    outline-offset: 2px;
  }
</style>
