// apps/frontend/src/features/quiz/components/QuestionDisplay.tsx
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import type { QuizQuestion } from '@lingua-quiz/core';
import type { LevelWordLists } from '@api/types';
import { LEVEL_CONFIG } from '../config/levelConfig';

interface QuestionDisplayProps {
  currentQuestion?: QuizQuestion | null;
  levelWordLists?: LevelWordLists;
}

export function QuestionDisplay({
  currentQuestion = null,
  levelWordLists = {},
}: QuestionDisplayProps): React.JSX.Element {
  const { t } = useTranslation();

  const questionLanguage = currentQuestion?.sourceLanguage ?? 'en';

  const levelInfo = useMemo(() => {
    if (currentQuestion === null) return null;
    const config = LEVEL_CONFIG.find((c) => c.key === currentQuestion.level);
    if (config === undefined) return null;
    return {
      label: config.label,
      description: config.description(currentQuestion.sourceLanguage, currentQuestion.targetLanguage),
      id: config.id,
    };
  }, [currentQuestion]);

  const totalWords = useMemo(
    () => Object.values(levelWordLists).reduce((sum, level) => sum + level.count, 0),
    [levelWordLists],
  );

  const currentLevelCount = useMemo(() => {
    if (levelInfo === null) return 0;
    return levelWordLists[levelInfo.id]?.count ?? 0;
  }, [levelInfo, levelWordLists]);

  const completionPercent = totalWords > 0 ? Math.round(((totalWords - currentLevelCount) / totalWords) * 100) : 0;

  if (currentQuestion === null) {
    return (
      <div className="flex flex-col items-center justify-center min-h-20 px-6 py-4 bg-muted/50 rounded-lg opacity-70">
        <span id="word" className="text-lg font-bold text-muted-foreground text-center">
          {t('quiz.noQuestions')}
        </span>
        <p className="text-sm text-muted-foreground mt-2">{t('quiz.noQuestionsDesc')}</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2">
      {levelInfo !== null && (
        <div className="flex justify-between items-center">
          <span className="text-sm text-muted-foreground">{levelInfo.description}</span>
          <output className="text-sm text-muted-foreground font-medium">{completionPercent}%</output>
        </div>
      )}
      {levelInfo !== null && (
        <progress
          className="w-full h-1.5 rounded-full appearance-none [&::-webkit-progress-bar]:rounded-full [&::-webkit-progress-bar]:bg-muted [&::-webkit-progress-value]:rounded-full [&::-webkit-progress-value]:bg-primary [&::-moz-progress-bar]:rounded-full [&::-moz-progress-bar]:bg-primary"
          value={completionPercent}
          max="100"
          aria-label={`Level completion: ${completionPercent}%`}
        >
          {completionPercent}%
        </progress>
      )}
      <div className="flex flex-col items-center justify-center min-h-20 px-6 py-4 bg-primary/5 rounded-lg">
        <span
          id="word"
          className="text-xl font-bold text-primary text-center wrap-break-word hyphens-auto"
          lang={questionLanguage}
        >
          {currentQuestion.questionText}
        </span>
      </div>
    </div>
  );
}

// packages/frontend/src/components/quiz/QuestionDisplay.svelte
<script lang="ts">
  import type { QuizQuestion } from '@lingua-quiz/core';
  import { LEVEL_CONFIG } from '../../lib/config/levelConfig';
  import { _ } from 'svelte-i18n';
  import type { LevelWordLists } from '../../api-types';

  interface Props {
    currentQuestion?: QuizQuestion | null;
    levelWordLists?: LevelWordLists;
  }

  const { currentQuestion = null, levelWordLists = {} }: Props = $props();

  const questionLanguage = $derived(currentQuestion?.sourceLanguage || 'en');

  const levelInfo = $derived.by(() => {
    if (!currentQuestion) return null;
    const config = LEVEL_CONFIG.find((c) => c.key === currentQuestion.level);
    if (!config) return null;
    return {
      label: config.label,
      description: config.description(currentQuestion.sourceLanguage, currentQuestion.targetLanguage),
      id: config.id,
    };
  });

  const totalWords = $derived(
    Object.values(levelWordLists).reduce((sum, level) => sum + level.count, 0),
  );

  const currentLevelCount = $derived.by(() => {
    if (!levelInfo) return 0;
    return levelWordLists[levelInfo.id]?.count ?? 0;
  });

  const completionPercent = $derived(
    totalWords > 0 ? Math.round(((totalWords - currentLevelCount) / totalWords) * 100) : 0,
  );
</script>

{#if currentQuestion}
  <div class="flex flex-col gap-2">
    {#if levelInfo}
      <div class="flex justify-between items-center">
        <span class="text-sm text-muted-foreground">{levelInfo.description}</span>
        <output class="text-sm text-muted-foreground font-medium">
          {completionPercent}%
        </output>
      </div>
      <progress
        class="w-full h-1.5 rounded-full appearance-none bg-muted
               [&::-webkit-progress-bar]:bg-muted
               [&::-webkit-progress-bar]:rounded-full
               [&::-webkit-progress-value]:bg-primary
               [&::-webkit-progress-value]:rounded-full
               [&::-webkit-progress-value]:transition-all
               [&::-moz-progress-bar]:bg-primary
               [&::-moz-progress-bar]:rounded-full"
        value={completionPercent}
        max="100"
        aria-label="Level completion: {completionPercent}%"
      >{completionPercent}%</progress>
    {/if}
    <div
      class="flex flex-col items-center justify-center min-h-20 px-6 py-4
             bg-primary/5 rounded-lg"
    >
      <span
        id="word"
        class="text-xl font-bold text-primary text-center break-words hyphens-auto"
        lang={questionLanguage}
      >
        {currentQuestion.questionText}
      </span>
    </div>
  </div>
{:else}
  <div
    class="flex flex-col items-center justify-center min-h-20 px-6 py-4
           bg-muted/50 rounded-lg opacity-70"
  >
    <span id="word" class="text-lg font-bold text-muted-foreground text-center">
      {$_('quiz.noQuestions')}
    </span>
    <p class="text-sm text-muted-foreground mt-2">
      {$_('quiz.noQuestionsDesc')}
    </p>
  </div>
{/if}
