// packages/frontend/src/features/quiz/components/TTSButton.tsx
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Volume2 } from 'lucide-react';
import { Button } from '@shared/ui';
import { ttsService, type TTSState } from '../services/tts-service';

interface TTSButtonProps {
  token: string;
  text: string;
  language: string;
}

export function TTSButton({ token, text, language }: TTSButtonProps): React.JSX.Element {
  const { t } = useTranslation();
  const [ttsState, setTtsState] = useState<TTSState>({
    isAvailable: false,
    supportedLanguages: [],
    isPlaying: false,
  });

  const canUseTTS = ttsService.canUseTTS(language);

  useEffect(() => {
    const unsubscribe = ttsService.subscribe((state) => {
      setTtsState(state);
    });

    return () => {
      unsubscribe();
      ttsService.stopCurrentAudio();
    };
  }, []);

  const handlePlay = () => {
    ttsService.playTTS(token, text, language);
  };

  if (!canUseTTS) {
    return (
      <span className="tts-muted text-sm text-muted-foreground" aria-live="polite">
        {t('quiz.ttsUnavailable', { language: language || 'this language' })}
      </span>
    );
  }

  return (
    <Button
      variant="outline"
      size="sm"
      className={ttsState.isPlaying ? 'speaking' : ''}
      onClick={handlePlay}
      disabled={ttsState.isPlaying}
      aria-label={t('quiz.listenPronunciation')}
    >
      <Volume2 size={16} />
      <span>{ttsState.isPlaying ? t('quiz.playing') : t('quiz.listen')}</span>
    </Button>
  );
}

// packages/frontend/src/components/quiz/TTSButton.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Button } from '$lib/components/ui/button';
  import { ttsService, type TTSState } from '../../lib/services/ttsService';
  import { Volume2 } from 'lucide-svelte';
  import { _ } from 'svelte-i18n';

  interface Props {
    token: string;
    text: string;
    language: string;
  }

  const { token, text, language }: Props = $props();

  let ttsState = $state<TTSState>({ isAvailable: false, supportedLanguages: [], isPlaying: false });

  const canUseTTS = $derived(ttsService.canUseTTS(language));

  onMount(() => {
    const unsubscribe = ttsService.subscribe((state) => {
      ttsState = state;
    });

    return () => {
      unsubscribe();
      ttsService.stopCurrentAudio();
    };
  });

  function handlePlay() {
    ttsService.playTTS(token, text, language);
  }
</script>

{#if canUseTTS}
  <Button
    variant="outline"
    size="sm"
    class={ttsState.isPlaying ? 'speaking' : ''}
    onclick={handlePlay}
    disabled={ttsState.isPlaying}
    aria-label={$_('quiz.listenPronunciation')}>
    <Volume2 size={16} />
    <span>{ttsState.isPlaying ? $_('quiz.playing') : $_('quiz.listen')}</span>
  </Button>
{:else}
  <span class="tts-muted text-sm" aria-live="polite">{$_('quiz.ttsUnavailable', { values: { language: language || 'this language' } })}</span>
{/if}

<style>
  .tts-muted {
    color: var(--color-text-muted);
  }
</style>
